add_newline = false

prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "golang",
    "java",
    "nodejs",
    "python",
    "rust",
    "conda",
    "aws",
    "battery",
    "time",
    "line_break",
    "directory",
    "cmd_duration",
    "character",
]

[battery]
full_symbol = ""
charging_symbol = " "
discharging_symbol = ""

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 60
style = "bold yellow"

[[battery.display]]
threshold = 99
style = "bold green"

[directory]
truncation_length = 8

[java]
symbol = " "

[hostname]
ssh_only = false
prefix = " ⟪"
suffix = "⟫"
trim_at = ".companyname.com"
disabled = false
style = "bold italic fg:purple"

[kubernetes]
symbol = "⛵ "
style = "dim green"
disabled = false

[python]
symbol = " "
style = "bold yellow"

[ruby]
disabled = true

[username]
disabled = false
show_always = true
style_root = "bold red"
style_user = "bold fg:14"

[time]
use_12hr = true
disabled = true
format = " [ %Y %b %d (%a) %I:%M%p ]"
utc_time_offset = -5
style = "bold blue"

[cmd_duration]
min_time = 1000
prefix = "省"
disabled = false

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[haskell]
disabled = true

[hg_branch]
disabled = true

[jobs]
disabled = true

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[php]
disabled = true
