#! /bin/sh
bspc monitor primary -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           30
bspc config border_radius        20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
## Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#--Autostart--#
if [[ ! `pgrep redshift` ]]; then
   redshift & 
fi

pbar &
picom &
xset b off
unclutter &
nm-applet &
low_battery &
dunst_start &
blueman-applet &
feh --bg-fill ~/.config/wall.png
xsetroot -cursor_name left_ptr &
setxkbmap -option caps:swapescape
sxhkd -c ~/.config/bspwm/sxhkdrc &
xinput set-prop Synaptics\ TM3096-006 "libinput Tapping Enabled" 1
# red &
# compton &
# dunst &
# mpd &
# xrdb ~/.Xdefaults
# xrdb ~/.Xresources
# deadd-notification-center &
