#! /bin/sh
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
## Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

#--Autostart--#
# wal -i ~/.config/wall.png -q -t -s &
#wal -R
xrdb ~/.Xdefaults
xrdb ~/.Xresources
pbar &
xsetroot -cursor_name left_ptr &
sxhkd -c ~/.config/bspwm/sxhkdrc &
xset b off
feh --bg-fill ~/.config/wall.png
setxkbmap -option caps:swapescape
red &
# picom &
compton &
unclutter &
pkill dunst
dunst &
#mpd &
nm-applet &
blueman-applet &
